# Generated by Django 3.2.3 on 2024-11-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
